'use client';

import * as React from 'react';
import { Card } from '@/components/ui/Card';
import { Button } from '@/components/ui/Button';
import { Badge } from '@/components/ui/Badge';
import { Skeleton } from '@/components/ui/Skeleton';

interface NewsPayload {
  brand_id: number;
  brand_name: string;
  model: string;
  generated_at: string;
  cached?: boolean;
  sections: {
    what_theyre_doing: string;
    what_theyre_launching: string;
    whos_joined: string;
    what_others_say: string;
    lenskart_take: string;
  };
}

function rel(d: string): string {
  const ms = Date.now() - new Date(d).getTime();
  const h = Math.floor(ms / 3600000);
  if (h < 1) return 'just now';
  if (h < 24) return `${h}h ago`;
  return `${Math.floor(h / 24)}d ago`;
}

export function BrandNews({ brandId }: { brandId: number }) {
  const [news, setNews] = React.useState<NewsPayload | null>(null);
  const [loading, setLoading] = React.useState(true);
  const [error, setError] = React.useState<string | null>(null);

  const fetchNews = React.useCallback(async (refresh = false) => {
    setLoading(true);
    setError(null);
    try {
      const res = await fetch(`/api/v1/brands/news?id=${brandId}${refresh ? '&refresh=1' : ''}`);
      const data = await res.json();
      if (data.error) setError(data.error);
      else setNews(data);
    } catch (e) {
      setError(e instanceof Error ? e.message : 'Failed');
    }
    setLoading(false);
  }, [brandId]);

  React.useEffect(() => { fetchNews(); }, [fetchNews]);

  if (loading && !news) {
    return <div className="max-w-4xl mx-auto px-4 py-6 space-y-4">
      {[1,2,3,4,5].map(i => <Skeleton key={i} className="h-24" />)}
    </div>;
  }
  if (error) return <div className="max-w-4xl mx-auto px-4 py-8 text-[13px] text-[var(--danger)]">{error}</div>;
  if (!news) return null;

  const sections: Array<{ key: keyof NewsPayload['sections']; title: string; tone: 'neutral' | 'accent' | 'success' | 'warn' | 'danger' }> = [
    { key: 'what_theyre_doing',      title: "What they're doing",      tone: 'neutral' },
    { key: 'what_theyre_launching',  title: "What they're launching",  tone: 'accent' },
    { key: 'whos_joined',            title: "Who's joined",            tone: 'success' },
    { key: 'what_others_say',        title: "What others say",         tone: 'neutral' },
    { key: 'lenskart_take',          title: 'Lenskart take',           tone: 'warn' },
  ];

  return (
    <div className="max-w-4xl mx-auto px-4 py-6">
      <div className="flex items-center justify-between mb-4">
        <div>
          <h2 className="text-[16px] font-semibold">Brand brief</h2>
          <div className="flex items-center gap-2 mt-0.5 text-[11px] text-[var(--ink-muted)]">
            <span>Generated by {news.model}</span>
            <span>·</span>
            <span>{rel(news.generated_at)}</span>
            {news.cached && <Badge size="xs">Cached</Badge>}
          </div>
        </div>
        <Button size="sm" variant="secondary" onClick={() => fetchNews(true)} loading={loading}>
          Regenerate
        </Button>
      </div>
      <div className="space-y-3">
        {sections.map(s => (
          <Card key={s.key} padding="md">
            <div className="flex items-center gap-2 mb-2">
              <Badge tone={s.tone}>{s.title}</Badge>
            </div>
            <p className="text-[13px] leading-relaxed text-[var(--ink)]">
              {news.sections[s.key]}
            </p>
          </Card>
        ))}
      </div>
    </div>
  );
}
